name: Build macOS Electron App

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'GitLab tag reference'
        required: true
        default: 'refs/tags/v1.0.0'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout minimal runner repo
        uses: actions/checkout@v3

      - name: Clone source code from GitLab
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/your-group/your-private-repo.git source-code
          ls source-code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./source-code
        run: npm ci

      - name: Build Electron macOS app
        working-directory: ./source-code
        run: npm run builder-mac

      - name: Upload release artifact (DMG)
        uses: actions/upload-artifact@v3
        with:
          name: macos-electron-app
          path: source-code/release-output/*.dmg
