name: GitLab to GitHub Release

on:
  push:
    tags:
      - "1.0.*"  # Trigger on tags like 1.0.1

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow creating releases

    steps:
      # 1. Clone from GitLab
      - name: Checkout GitLab repo
        uses: actions/checkout@v4
        with:
          repository: gitlab.com/yoongnan/dynamike-tools
          ssh-key: ${{ secrets.GITLAB_SSH_KEY }}
          fetch-depth: 0

      # 2. Build Electron app
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: |
          npm run build-prod
          npm run builder -- --win --mac  # Only build .exe/.dmg

      # 3. Release to GitHub
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-output/*.exe
            release-output/*.dmg
            release-output/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-injected
