name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'GitLab Tag'
        required: true
        default: ''

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Install nvm and Node.js
        run: |
          # Install nvm (Node Version Manager)
          export NVM_DIR="$HOME/.nvm"
          mkdir -p $NVM_DIR
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          source $NVM_DIR/nvm.sh
          
          # Install Node.js version 16.7.0
          nvm install 16.7.0
          nvm use 16.7.0
          
          # Verify Node.js and npm installation
          node -v
          npm -v

      - name: Clone GitLab repo and build
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/yoongnan/dynamike-tools.git
          cd dynamike-tools
          npm ci --legacy-peer-deps
          npm update
          npm run build-prod
          npm run builder-mac

          # Move output before cleanup (adjust path if needed)
          mkdir -p ../release-output
          mv release-output/*.dmg release-output/*.yml ../release-output/

          # Clean up source code
          cd ..
          rm -rf dynamike-tools

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: macos-build
      #     path: release-output/
