name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'GitLab Tag'
        required: true
        default: ''

jobs:
  create-tag-and-build:
    runs-on: macos-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Check if tag exists on GitHub
        id: check_tag
        run: |
          TAG_EXISTS=$(curl --silent --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/ChinYoongNan/dynamike-tools/tags" | grep -o "1.0.0")
          echo "Tag exists: $TAG_EXISTS"
          if [ -z "$TAG_EXISTS" ]; then
            echo "Tag does not exist. Creating and pushing tag."
            git tag 1.0.0
            git push origin 1.0.0
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clone GitLab repo and build
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/your-group/your-private-repo.git source-code
          cd source-code
          npm ci
          npm run builder-mac

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: source-code/release-output/*.dmg
