name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'GitLab Tag'
        required: true
        default: ''

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Install nvm and Node.js
        run: |
          # Install nvm (Node Version Manager)
          export NVM_DIR="$HOME/.nvm"
          mkdir -p $NVM_DIR
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          source $NVM_DIR/nvm.sh
          
          # Install Node.js version 16.7.0
          nvm install 16.7.0
          nvm use 16.7.0
          
          # Verify Node.js and npm installation
          node -v
          npm -v

      - name: Clone GitLab repo and build
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/your-group/your-private-repo.git source-code
          cd source-code
          npm ci
          npm run builder-mac
